export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import '@/app/globals.css';
import { AuthProvider } from "@/utils/authContext"

export default function RootLayout({
  children,
}: {
  children: React.ReactElement
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
        {children}
        </AuthProvider>
        </body>
    </html>
  )
}
